package ceedubs.config.readers

trait AllValueReaderInstances extends AnyValConfigValueReaders with StringConfigValueReader with OptionConfigValueReaders
    with CollectionConfigValueReaders

object AllValueReaderInstances extends AllValueReaderInstances
